package rules.ChampionRecommender;
dialect  "mvel"

import com.example.demo.Model.Champion;
import com.example.demo.Model.ChampionRecommendSession;
import com.example.demo.Model.Enums.*;

rule "Recommend champion based on Playstyle preference, ROAMING"
agenda-group "midlane"
    when
        $champion: Champion($name: name, playstyle == Playstyle.ROAMING)
        $session: ChampionRecommendSession($championList: championList)
    then
        modify($session){ updateScore($champion, 10)}

end

rule "Recommend champion based on Playstyle preference, ROAMING"
agenda-group "midlane"
    when
        $champion: Champion($name: name, playstyle == Playstyle.ROAMING)
        $session: ChampionRecommendSession($championList: championList)
    then
        modify($session){ updateScore($champion, 5)}

end

rule "Recommend champion based on Playstyle preference, SPLITPUSHING"
agenda-group "midlane"
    when
        $champion: Champion($name: name, playstyle == Playstyle.SPLITPUSHING)
        $session: ChampionRecommendSession($championList: championList)
    then
        modify($session){ updateScore($champion, 10)}

end

rule "Recommend champion based on Playstyle preference, SPLITPUSHING"
agenda-group "midlane"
    when
        $champion: Champion($name: name, playstyle == Playstyle.SPLITPUSHING)
        $session: ChampionRecommendSession($championList: championList)
    then
        modify($session){ updateScore($champion, 5)}

end

rule "Recommend champion based on Playstyle preference, TEAMFIGHTING"
agenda-group "midlane"
    when
        $champion: Champion($name: name, playstyle == Playstyle.TEAMFIGHTING)
        $session: ChampionRecommendSession($championList: championList)
    then
        modify($session){ updateScore($champion, 10)}

end

rule "Recommend champion based on Playstyle preference, TEAMFIGHTING"
agenda-group "midlane"
    when
        $champion: Champion($name: name, playstyle == Playstyle.TEAMFIGHTING)
        $session: ChampionRecommendSession($championList: championList)
    then
        modify($session){ updateScore($champion, 5)}

end
