package ChampionRecommender.AbilityResourceRules;
dialect  "mvel"

import com.example.demo.Model.*;
import com.example.demo.Model.ChampionRecommendSession;
import com.example.demo.Model.Enums.*;

rule "Recommend champion based on Ability resource, MANA"
agenda-group "mana"
no-loop
    when
        $champion: Champion($name: name, abilityResource == AbilityResource.MANA, abilityResourceChecked == false)
        $session: ChampionRecommendSession($championList: championList)
        $answers: ChampionRecommendAnswers(prefAbilityResource == AbilityResource.MANA)
    then
        modify($session){ updateScore($champion, 5)}
        modify($champion){ setAbilityResourceChecked(true)}
end


rule "Recommend champion based on Ability resource, ENERGY"
agenda-group "energy"
no-loop
    when
        $champion: Champion($name: name, abilityResource == AbilityResource.ENERGY, abilityResourceChecked == false)
        $session: ChampionRecommendSession($championList: championList)
        $answers: ChampionRecommendAnswers(prefAbilityResource == AbilityResource.ENERGY)
    then

        modify($session){ updateScore($champion, 5)}
        modify($champion){ setAbilityResourceChecked(true)}
end


rule "Recommend champion based on Ability resource, NOTHING"
agenda-group "nothing"
no-loop
    when
        $champion: Champion($name: name, abilityResource == AbilityResource.NOTHING, abilityResourceChecked == false)
        $session: ChampionRecommendSession($championList: championList)
        $answers: ChampionRecommendAnswers(prefAbilityResource == AbilityResource.NOTHING)
    then

        modify($session){ updateScore($champion, 5)}
        modify($champion){ setAbilityResourceChecked(true)}
end


rule "Recommend champion based on Ability resource, OTHER"
agenda-group "other"
no-loop
    when
        $champion: Champion($name: name, abilityResource == AbilityResource.OTHER, abilityResourceChecked == false)
        $session: ChampionRecommendSession($championList: championList)
        $answers: ChampionRecommendAnswers(prefAbilityResource == AbilityResource.OTHER)
    then
        modify($session){ updateScore($champion, 5)}
        modify($champion){ setAbilityResourceChecked(true)}
end
