package BuildRecommender.SituationalItemRules;
dialect  "mvel"

import com.example.demo.Model.Item
import com.example.demo.Model.Champion
import com.example.demo.Model.Enums.ItemSlot
import com.example.demo.Model.ItemRecommendSession
import com.example.demo.Model.Enums.ItemSlot
import com.example.demo.Model.Enums.*

rule "Recomending situational item that is good against enemy champion's class , for tanks"
salience 10
no-loop
     when
            $item: Item(itemSlot == ItemSlot.SITUATIONAL, name == "Warmorgs's Armor" ) // dobar protiv protivnicke klase ali za tankove
            $session: ItemRecommendSession($fullBuild: fullBuild, $pickedChampion: pickedChampion, situationalItemGiven == false)
            Champion(primaryClass == ChampionClass.TANK) from $pickedChampion
        then
            modify($session){ fullBuild.setSituationalItem($item)}
            modify($session){ setSituationalItemGiven(true)}
end

rule "Recomending situational item that is good against enemy champion's class , for AD champions"
salience 1
no-loop
     when
            $item: Item(itemSlot == ItemSlot.SITUATIONAL, $goodAgainstClass:goodAgainstClass, isForAD()) // dobar protiv protivnicke klase ali za AD champione
            $session: ItemRecommendSession($fullBuild: fullBuild, $enemyChampion: enemyChampion, $pickedChampion: pickedChampion, situationalItemGiven == false)
            Champion($enemyClass: primaryClass  == $goodAgainstClass) from $enemyChampion
            Champion(damageType.getPhysicalDamage() > 50) from $pickedChampion
        then
            modify($session){ fullBuild.setSituationalItem($item)}
            modify($session){ setSituationalItemGiven(true)}
end

rule "Recomending situational item that is good against enemy champion's class , for AP champions"
salience 1
no-loop
     when
            $item: Item(itemSlot == ItemSlot.SITUATIONAL, $goodAgainstClass: goodAgainstClass , isForAP()) // dobar protiv protivnicke klase ali za AP champione
            $session: ItemRecommendSession($fullBuild: fullBuild, $enemyChampion: enemyChampion, $pickedChampion: pickedChampion, situationalItemGiven == false)
            Champion($enemyClass: primaryClass == $goodAgainstClass) from $enemyChampion
            Champion(damageType.getMagicDamage() > 50) from $pickedChampion
        then
            modify($session){ fullBuild.setSituationalItem($item)}
            modify($session){ setSituationalItemGiven(true)}
end

