package ChampionRecommender.PlaystyleRules;
dialect  "mvel"

import com.example.demo.Model.*;
import com.example.demo.Model.ChampionRecommendSession;
import com.example.demo.Model.Enums.*;

rule "Recommend champion based on Playstyle preference, ROAMING"
agenda-group "roaming"
no-loop
    when
        $champion: Champion($name: name, playstyle == Playstyle.ROAMING, playstyleChecked == false)
        $session: ChampionRecommendSession($championList: championList)
        $answers: ChampionRecommendAnswers(prefPlaystyle == Playstyle.ROAMING)
    then
        modify($session){ updateScore($champion, 5)}
        modify($champion){ setPlaystyleChecked(true)}

end

rule "Recommend champion based on Playstyle preference, SPLITPUSHING"
agenda-group "splitpushing"
no-loop
    when
        $champion: Champion($name: name, playstyle == Playstyle.SPLITPUSHING, playstyleChecked == false)
        $session: ChampionRecommendSession($championList: championList)
        $answers: ChampionRecommendAnswers(prefPlaystyle == Playstyle.SPLITPUSHING)
    then
        modify($session){ updateScore($champion, 5)}
        modify($champion){ setPlaystyleChecked(true)}

end

rule "Recommend champion based on Playstyle preference, TEAMFIGHTING"
agenda-group "teamfighting"
no-loop
    when
        $champion: Champion($name: name, playstyle == Playstyle.TEAMFIGHTING, playstyleChecked == false)
        $session: ChampionRecommendSession($championList: championList)
        $answers: ChampionRecommendAnswers(prefPlaystyle == Playstyle.TEAMFIGHTING)
    then
        modify($session){ updateScore($champion, 5)}
        modify($champion){ setPlaystyleChecked(true)}

end
